// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvJUVfAvwvLvz6rzwTq-Az3fLNLssY9_I',
    appId: '1:600432874904:web:4db0c11179162c7d3b47ed',
    messagingSenderId: '600432874904',
    projectId: 'okuma-pusulasi',
    authDomain: 'okuma-pusulasi.firebaseapp.com',
    storageBucket: 'okuma-pusulasi.firebasestorage.app',
    measurementId: 'G-1TP1KGT7XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3yyQDAaT0S4HClzPsSo8N6IejenNKoEI',
    appId: '1:600432874904:android:7334fb2a7af774873b47ed',
    messagingSenderId: '600432874904',
    projectId: 'okuma-pusulasi',
    storageBucket: 'okuma-pusulasi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS_zbHgr2vOkFKXYG2FA0-Em2n1zl_QEI',
    appId: '1:600432874904:ios:080a929d45ce20e23b47ed',
    messagingSenderId: '600432874904',
    projectId: 'okuma-pusulasi',
    storageBucket: 'okuma-pusulasi.firebasestorage.app',
    iosBundleId: 'com.example.okumaPusulasi3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS_zbHgr2vOkFKXYG2FA0-Em2n1zl_QEI',
    appId: '1:600432874904:ios:080a929d45ce20e23b47ed',
    messagingSenderId: '600432874904',
    projectId: 'okuma-pusulasi',
    storageBucket: 'okuma-pusulasi.firebasestorage.app',
    iosBundleId: 'com.example.okumaPusulasi3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvJUVfAvwvLvz6rzwTq-Az3fLNLssY9_I',
    appId: '1:600432874904:web:abe5c467c5b813ec3b47ed',
    messagingSenderId: '600432874904',
    projectId: 'okuma-pusulasi',
    authDomain: 'okuma-pusulasi.firebaseapp.com',
    storageBucket: 'okuma-pusulasi.firebasestorage.app',
    measurementId: 'G-KNJEPC4ECK',
  );
}
